//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.17 at 05:49:42 AM CEST 
//


package xb.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xb.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME = new QName("http://www.skupstinans.rs", "Sadrzaj");
    private final static QName _TOdredbaPodtackaAlinejaTekstRef_QNAME = new QName("http://www.skupstinans.rs", "Ref");
    
    private final static QName _ClanTekst_QNAME = new QName("http://www.skupstinans.rs", "Tekst");
    private final static QName _ClanStav_QNAME = new QName("http://www.skupstinans.rs", "Stav");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xb.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TOdredba }
     * 
     */
    public TOdredba createTOdredba() {
        return new TOdredba();
    }

    /**
     * Create an instance of {@link TOdredba.Clan }
     * 
     */
    public TOdredba.Clan createTOdredbaClan() {
        return new TOdredba.Clan();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav }
     * 
     */
    public TOdredba.Clan.Stav createTOdredbaClanStav() {
        return new TOdredba.Clan.Stav();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav.Tacka }
     * 
     */
    public TOdredba.Clan.Stav.Tacka createTOdredbaClanStavTacka() {
        return new TOdredba.Clan.Stav.Tacka();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav.Tacka.Podtacka }
     * 
     */
    public TOdredba.Clan.Stav.Tacka.Podtacka createTOdredbaClanStavTackaPodtacka() {
        return new TOdredba.Clan.Stav.Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav.Tacka.Podtacka.Alineja }
     * 
     */
    public TOdredba.Clan.Stav.Tacka.Podtacka.Alineja createTOdredbaClanStavTackaPodtackaAlineja() {
        return new TOdredba.Clan.Stav.Tacka.Podtacka.Alineja();
    }

    /**
     * Create an instance of {@link TOdredba.Stav }
     * 
     */
    public TOdredba.Stav createTOdredbaStav() {
        return new TOdredba.Stav();
    }

    /**
     * Create an instance of {@link TOdredba.Stav.Tacka }
     * 
     */
    public TOdredba.Stav.Tacka createTOdredbaStavTacka() {
        return new TOdredba.Stav.Tacka();
    }

    /**
     * Create an instance of {@link TOdredba.Stav.Tacka.Podtacka }
     * 
     */
    public TOdredba.Stav.Tacka.Podtacka createTOdredbaStavTackaPodtacka() {
        return new TOdredba.Stav.Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link TOdredba.Stav.Tacka.Podtacka.Alineja }
     * 
     */
    public TOdredba.Stav.Tacka.Podtacka.Alineja createTOdredbaStavTackaPodtackaAlineja() {
        return new TOdredba.Stav.Tacka.Podtacka.Alineja();
    }

    /**
     * Create an instance of {@link TOdredba.Tacka }
     * 
     */
    public TOdredba.Tacka createTOdredbaTacka() {
        return new TOdredba.Tacka();
    }

    /**
     * Create an instance of {@link TOdredba.Tacka.Podtacka }
     * 
     */
    public TOdredba.Tacka.Podtacka createTOdredbaTackaPodtacka() {
        return new TOdredba.Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link TOdredba.Tacka.Podtacka.Alineja }
     * 
     */
    public TOdredba.Tacka.Podtacka.Alineja createTOdredbaTackaPodtackaAlineja() {
        return new TOdredba.Tacka.Podtacka.Alineja();
    }

    /**
     * Create an instance of {@link TOdredba.Podtacka }
     * 
     */
    public TOdredba.Podtacka createTOdredbaPodtacka() {
        return new TOdredba.Podtacka();
    }

    /**
     * Create an instance of {@link TOdredba.Podtacka.Alineja }
     * 
     */
    public TOdredba.Podtacka.Alineja createTOdredbaPodtackaAlineja() {
        return new TOdredba.Podtacka.Alineja();
    }

    /**
     * Create an instance of {@link TOdredba.Alineja }
     * 
     */
    public TOdredba.Alineja createTOdredbaAlineja() {
        return new TOdredba.Alineja();
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Tekst }
     * 
     */
    public TOdredba.Clan.Tekst createTOdredbaClanTekst() {
        return new TOdredba.Clan.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav.Tekst }
     * 
     */
    public TOdredba.Clan.Stav.Tekst createTOdredbaClanStavTekst() {
        return new TOdredba.Clan.Stav.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav.Tacka.Tekst }
     * 
     */
    public TOdredba.Clan.Stav.Tacka.Tekst createTOdredbaClanStavTackaTekst() {
        return new TOdredba.Clan.Stav.Tacka.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav.Tacka.Podtacka.Tekst }
     * 
     */
    public TOdredba.Clan.Stav.Tacka.Podtacka.Tekst createTOdredbaClanStavTackaPodtackaTekst() {
        return new TOdredba.Clan.Stav.Tacka.Podtacka.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Clan.Stav.Tacka.Podtacka.Alineja.Tekst }
     * 
     */
    public TOdredba.Clan.Stav.Tacka.Podtacka.Alineja.Tekst createTOdredbaClanStavTackaPodtackaAlinejaTekst() {
        return new TOdredba.Clan.Stav.Tacka.Podtacka.Alineja.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Stav.Tekst }
     * 
     */
    public TOdredba.Stav.Tekst createTOdredbaStavTekst() {
        return new TOdredba.Stav.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Stav.Tacka.Tekst }
     * 
     */
    public TOdredba.Stav.Tacka.Tekst createTOdredbaStavTackaTekst() {
        return new TOdredba.Stav.Tacka.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Stav.Tacka.Podtacka.Tekst }
     * 
     */
    public TOdredba.Stav.Tacka.Podtacka.Tekst createTOdredbaStavTackaPodtackaTekst() {
        return new TOdredba.Stav.Tacka.Podtacka.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Stav.Tacka.Podtacka.Alineja.Tekst }
     * 
     */
    public TOdredba.Stav.Tacka.Podtacka.Alineja.Tekst createTOdredbaStavTackaPodtackaAlinejaTekst() {
        return new TOdredba.Stav.Tacka.Podtacka.Alineja.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Tacka.Tekst }
     * 
     */
    public TOdredba.Tacka.Tekst createTOdredbaTackaTekst() {
        return new TOdredba.Tacka.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Tacka.Podtacka.Tekst }
     * 
     */
    public TOdredba.Tacka.Podtacka.Tekst createTOdredbaTackaPodtackaTekst() {
        return new TOdredba.Tacka.Podtacka.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Tacka.Podtacka.Alineja.Tekst }
     * 
     */
    public TOdredba.Tacka.Podtacka.Alineja.Tekst createTOdredbaTackaPodtackaAlinejaTekst() {
        return new TOdredba.Tacka.Podtacka.Alineja.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Podtacka.Tekst }
     * 
     */
    public TOdredba.Podtacka.Tekst createTOdredbaPodtackaTekst() {
        return new TOdredba.Podtacka.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Podtacka.Alineja.Tekst }
     * 
     */
    public TOdredba.Podtacka.Alineja.Tekst createTOdredbaPodtackaAlinejaTekst() {
        return new TOdredba.Podtacka.Alineja.Tekst();
    }

    /**
     * Create an instance of {@link TOdredba.Alineja.Tekst }
     * 
     */
    public TOdredba.Alineja.Tekst createTOdredbaAlinejaTekst() {
        return new TOdredba.Alineja.Tekst();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Podtacka.Alineja.Tekst.class)
    public JAXBElement<String> createTOdredbaPodtackaAlinejaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Podtacka.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Podtacka.Alineja.Tekst.class)
    public JAXBElement<Object> createTOdredbaPodtackaAlinejaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Podtacka.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Tacka.Tekst.class)
    public JAXBElement<String> createTOdredbaTackaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Tacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Tacka.Tekst.class)
    public JAXBElement<Object> createTOdredbaTackaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Tacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Clan.Stav.Tacka.Podtacka.Tekst.class)
    public JAXBElement<String> createTOdredbaClanStavTackaPodtackaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Clan.Stav.Tacka.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Clan.Stav.Tacka.Podtacka.Tekst.class)
    public JAXBElement<Object> createTOdredbaClanStavTackaPodtackaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Clan.Stav.Tacka.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Clan.Stav.Tekst.class)
    public JAXBElement<String> createTOdredbaClanStavTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Clan.Stav.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Clan.Stav.Tekst.class)
    public JAXBElement<Object> createTOdredbaClanStavTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Clan.Stav.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Clan.Stav.Tacka.Tekst.class)
    public JAXBElement<String> createTOdredbaClanStavTackaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Clan.Stav.Tacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Clan.Stav.Tacka.Tekst.class)
    public JAXBElement<Object> createTOdredbaClanStavTackaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Clan.Stav.Tacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Clan.Stav.Tacka.Podtacka.Alineja.Tekst.class)
    public JAXBElement<String> createTOdredbaClanStavTackaPodtackaAlinejaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Clan.Stav.Tacka.Podtacka.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Clan.Stav.Tacka.Podtacka.Alineja.Tekst.class)
    public JAXBElement<Object> createTOdredbaClanStavTackaPodtackaAlinejaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Clan.Stav.Tacka.Podtacka.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Podtacka.Tekst.class)
    public JAXBElement<String> createTOdredbaPodtackaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Podtacka.Tekst.class)
    public JAXBElement<Object> createTOdredbaPodtackaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Stav.Tekst.class)
    public JAXBElement<String> createTOdredbaStavTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Stav.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Stav.Tekst.class)
    public JAXBElement<Object> createTOdredbaStavTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Stav.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Alineja.Tekst.class)
    public JAXBElement<String> createTOdredbaAlinejaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Alineja.Tekst.class)
    public JAXBElement<Object> createTOdredbaAlinejaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Stav.Tacka.Podtacka.Alineja.Tekst.class)
    public JAXBElement<String> createTOdredbaStavTackaPodtackaAlinejaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Stav.Tacka.Podtacka.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Stav.Tacka.Podtacka.Alineja.Tekst.class)
    public JAXBElement<Object> createTOdredbaStavTackaPodtackaAlinejaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Stav.Tacka.Podtacka.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Tacka.Podtacka.Tekst.class)
    public JAXBElement<String> createTOdredbaTackaPodtackaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Tacka.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Tacka.Podtacka.Tekst.class)
    public JAXBElement<Object> createTOdredbaTackaPodtackaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Tacka.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Stav.Tacka.Tekst.class)
    public JAXBElement<String> createTOdredbaStavTackaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Stav.Tacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Stav.Tacka.Tekst.class)
    public JAXBElement<Object> createTOdredbaStavTackaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Stav.Tacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Stav.Tacka.Podtacka.Tekst.class)
    public JAXBElement<String> createTOdredbaStavTackaPodtackaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Stav.Tacka.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Stav.Tacka.Podtacka.Tekst.class)
    public JAXBElement<Object> createTOdredbaStavTackaPodtackaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Stav.Tacka.Podtacka.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Clan.Tekst.class)
    public JAXBElement<String> createTOdredbaClanTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Clan.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Clan.Tekst.class)
    public JAXBElement<Object> createTOdredbaClanTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Clan.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Sadrzaj", scope = TOdredba.Tacka.Podtacka.Alineja.Tekst.class)
    public JAXBElement<String> createTOdredbaTackaPodtackaAlinejaTekstSadrzaj(String value) {
        return new JAXBElement<String>(_TOdredbaPodtackaAlinejaTekstSadrzaj_QNAME, String.class, TOdredba.Tacka.Podtacka.Alineja.Tekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Ref", scope = TOdredba.Tacka.Podtacka.Alineja.Tekst.class)
    public JAXBElement<Object> createTOdredbaTackaPodtackaAlinejaTekstRef(Object value) {
        return new JAXBElement<Object>(_TOdredbaPodtackaAlinejaTekstRef_QNAME, Object.class, TOdredba.Tacka.Podtacka.Alineja.Tekst.class, value);
    }
    
    /**
     * Create an instance of {@link Korisnici }
     * 
     */
    public Korisnici createKorisnici() {
        return new Korisnici();
    }

    /**
     * Create an instance of {@link TipKorisnik }
     * 
     */
    public TipKorisnik createTipKorisnik() {
        return new TipKorisnik();
    }
    
    /**
     * Create an instance of {@link Zakon }
     * 
     */
    public Zakon createZakon() {
        return new Zakon();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Clan.Stav }
     * 
     */
    public Clan.Stav createClanStav() {
        return new Clan.Stav();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka }
     * 
     */
    public Clan.Stav.Tacka createClanStavTacka() {
        return new Clan.Stav.Tacka();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Podtacka }
     * 
     */
    public Clan.Stav.Tacka.Podtacka createClanStavTackaPodtacka() {
        return new Clan.Stav.Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Podtacka.Alineja }
     * 
     */
    public Clan.Stav.Tacka.Podtacka.Alineja createClanStavTackaPodtackaAlineja() {
        return new Clan.Stav.Tacka.Podtacka.Alineja();
    }

    /**
     * Create an instance of {@link Zakon.Deo }
     * 
     */
    public Zakon.Deo createZakonDeo() {
        return new Zakon.Deo();
    }

    /**
     * Create an instance of {@link Zakon.Deo.Glava }
     * 
     */
    public Zakon.Deo.Glava createZakonDeoGlava() {
        return new Zakon.Deo.Glava();
    }

    /**
     * Create an instance of {@link Zakon.Deo.Glava.Odeljak }
     * 
     */
    public Zakon.Deo.Glava.Odeljak createZakonDeoGlavaOdeljak() {
        return new Zakon.Deo.Glava.Odeljak();
    }

    /**
     * Create an instance of {@link Clan.Tekst }
     * 
     */
    public Clan.Tekst createClanTekst() {
        return new Clan.Tekst();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tekst }
     * 
     */
    public Clan.Stav.Tekst createClanStavTekst() {
        return new Clan.Stav.Tekst();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Tekst }
     * 
     */
    public Clan.Stav.Tacka.Tekst createClanStavTackaTekst() {
        return new Clan.Stav.Tacka.Tekst();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Podtacka.Tekst }
     * 
     */
    public Clan.Stav.Tacka.Podtacka.Tekst createClanStavTackaPodtackaTekst() {
        return new Clan.Stav.Tacka.Podtacka.Tekst();
    }

    /**
     * Create an instance of {@link Clan.Stav.Tacka.Podtacka.Alineja.Tekst }
     * 
     */
    public Clan.Stav.Tacka.Podtacka.Alineja.Tekst createClanStavTackaPodtackaAlinejaTekst() {
        return new Clan.Stav.Tacka.Podtacka.Alineja.Tekst();
    }

    /**
     * Create an instance of {@link Zakon.Deo.Glava.Odeljak.Pododeljak }
     * 
     */
    public Zakon.Deo.Glava.Odeljak.Pododeljak createZakonDeoGlavaOdeljakPododeljak() {
        return new Zakon.Deo.Glava.Odeljak.Pododeljak();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan.Tekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Tekst", scope = Clan.class)
    public JAXBElement<Clan.Tekst> createClanTekst(Clan.Tekst value) {
        return new JAXBElement<Clan.Tekst>(_ClanTekst_QNAME, Clan.Tekst.class, Clan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Clan.Stav }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.skupstinans.rs", name = "Stav", scope = Clan.class)
    public JAXBElement<Clan.Stav> createClanStav(Clan.Stav value) {
        return new JAXBElement<Clan.Stav>(_ClanStav_QNAME, Clan.Stav.class, Clan.class, value);
    }

}
