//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.10 at 04:47:37 PM CEST 
//


package xb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipPredsednik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipPredsednik">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.skupstinans.rs/tipovi}TipOdbornik">
 *       &lt;sequence>
 *         &lt;element name="Mandat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipPredsednik", propOrder = {
    "mandat"
})
public class TipPredsednik
    extends TipOdbornik
{

    @XmlElement(name = "Mandat", required = true)
    protected String mandat;

    /**
     * Gets the value of the mandat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMandat() {
        return mandat;
    }

    /**
     * Sets the value of the mandat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMandat(String value) {
        this.mandat = value;
    }

}
